language: java
java:
  - 1.8

script: junit Teste.java

notifications:
  slack: bsi-ifes:nECNqvrLZq1fjJz6C88BjfXk
  
script:
  - sonar-scanner -Dsonar.login=$c85312f9026df6e3a31e017fa5c14b0c43258993 
